name: Clone DB Job

on:
  workflow_call:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: number
      changed_services:
        description: "JSON array of changed services"
        required: true
        type: string

jobs:
  clone-db:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Clone Order DB
        if: contains(fromJson(inputs.changed_services), 'order-service')
        run: bash ./scripts/clone_db.sh order-service ${{ inputs.pr_number }}

      - name: Clone Inventory DB
        if: contains(fromJson(inputs.changed_services), 'inventory-service')
        run: bash ./scripts/clone_db.sh inventory-service ${{ inputs.pr_number }}

      - name: Clone Notification DB
        if: contains(fromJson(inputs.changed_services), 'notification-service')
        run: bash ./scripts/clone_db.sh notification-service ${{ inputs.pr_number }}
