name: Changes Job

on:
  workflow_call:
    outputs:
      changed_services:
        description: "JSON array of changed services"
        value: ${{ jobs.changes.outputs.changed_services }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            order-service:
              - 'app/order-service/**'
            inventory-service:
              - 'app/inventory-service/**'
            notification-service:
              - 'app/notification-service/**'
            frontend:
              - 'app/frontend/**'
